spring:
  application:
    name: config-server
  profiles:
    active: git, vault
  cloud:
    config:
      server:
        vault:
          host: ${LHOST}
          port: 8200
          scheme: http
          authentication: token
          token: ${VAULT_TOKEN}
          kv-version: 2
          kv:
            enabled: true
            backend: secret
        git:
          uri: ${GIT_CONFIG_REPOSITORY_URI}
          username: ${GIT_USERNAME}
          password: ${GIT_PAT}
          default-label: main
          clone-on-start: true

server:
  port: 8203