spring:
  application:
    name: config-server
  profiles:
    active: composite
  cloud:
    config:
      server:
        composite:
        - type: vault
          host: localhost
          port: 8200
          scheme: http
          authentication: token
          token: ${VAULT_TOKEN}
          kv-version: 2
          kv:
            enabled: true
            backend: secret
        - type: git
          uri: ${GIT_CONFIG_REPOSITORY_URI}
          username: ${GIT_USERNAME}
          password: ${GIT_PAT}
          default-label: main
          clone-on-start: true

server:
  port: 8203