global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'microservices'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'config-server:8203'
          - 'discovery-server:8761'
          - 'api-gateway:8202'
          - 'user-service:8080'
          - 'product-service:8081'
          - 'order-service:8082'
          - 'auth-service:8083'
          - 'cart-service:8084'
          - 'notification-service:8085'
          - 'payment-service:8086'