spring:
  cloud:
    config:
      server:
        vault:
          host: ${LHOST}
          port: ${VAULT_PORT}
          scheme: http
          authentication: token
          token: ${VAULT_TOKEN}
          kv-version: 2
          kv:
            enabled: true
            backend: secret
        git:
          uri: ${GIT_CONFIG_REPOSITORY_URI}
          username: ${GIT_USERNAME}
          password: ${GIT_PAT}
          default-label: main
          clone-on-start: true