# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build config-server
        working-directory: ./config-server
        run: ./gradlew build

      - name: Build discovery-server
        working-directory: ./discovery-server
        run: ./gradlew build

      - name: Build user-service
        working-directory: ./user-service
        run: ./gradlew build

      - name: Build auth-service
        working-directory: ./auth-service
        run: ./gradlew build

      - name: Build product-service
        working-directory: ./product-service
        run: ./gradlew build

      - name: Build cart-service
        working-directory: ./cart-service
        run: ./gradlew build

      - name: Build order-service
        working-directory: ./order-service
        run: ./gradlew build

      - name: Build payment-service
        working-directory: ./payment-service
        run: ./gradlew build

      - name: Build notification-service
        working-directory: ./notification-service
        run: ./gradlew build

      - name: Build api-gateway
        working-directory: ./api-gateway
        run: ./gradlew build
